import React, { useState } from 'react';
import { BookOpen, Search, Filter, ShieldAlert, Sparkles, Check, CheckSquare, Square, Layers, CircleCheck, Play } from 'lucide-react';
import { Question, ExamLanguage, ExamDifficulty } from '../types';

interface QuestionBankViewProps {
  questions: Question[];
  onAssembleTest: (selectedQuestions: Question[]) => void;
}

export default function QuestionBankView({ questions, onAssembleTest }: QuestionBankViewProps) {
  const [searchTerm, setSearchTerm] = useState('');
  const [subjectFilter, setSubjectFilter] = useState<string>('all');
  const [langFilter, setLangFilter] = useState<string>('all');
  const [diffFilter, setDiffFilter] = useState<string>('all');
  const [selectedIds, setSelectedIds] = useState<Record<string, boolean>>({});

  // Unique list of subjects for filters
  const subjectsList = ['all', ...Array.from(new Set(questions.map(q => q.subject)))];

  // Apply filters
  const filteredQuestions = questions.filter(q => {
    const matchesSearch = q.text.toLowerCase().includes(searchTerm.toLowerCase()) || 
                          q.explanation.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesSubject = subjectFilter === 'all' || q.subject === subjectFilter;
    const matchesLang = langFilter === 'all' || q.language === langFilter;
    const matchesDiff = diffFilter === 'all' || q.difficulty === diffFilter;

    return matchesSearch && matchesSubject && matchesLang && matchesDiff;
  });

  const toggleSelect = (id: string) => {
    setSelectedIds(prev => ({
      ...prev,
      [id]: !prev[id]
    }));
  };

  const toggleSelectAll = () => {
    const allSelectedInFilter = filteredQuestions.every(q => selectedIds[q.id]);
    const newState: Record<string, boolean> = { ...selectedIds };
    
    filteredQuestions.forEach(q => {
      newState[q.id] = !allSelectedInFilter;
    });

    setSelectedIds(newState);
  };

  const handleAssemble = () => {
    const chosen = questions.filter(q => selectedIds[q.id]);
    if (chosen.length > 0) {
      onAssembleTest(chosen);
    }
  };

  const selectedCount = Object.keys(selectedIds).filter(id => selectedIds[id]).length;

  return (
    <div className="space-y-6 animate-fadeIn max-w-5xl mx-auto">
      <div className="space-y-1">
        <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-800 tracking-tight flex items-center gap-2">
          <Layers className="h-6.5 w-6.5 text-indigo-500" />
          Question Repository Bank
        </h1>
        <p className="text-slate-500 max-w-2xl text-xs sm:text-sm">
          Browse and reuse all approved questions generated by AI. Select a specific custom list to package them into an immediate revision practice block.
        </p>
      </div>

      {/* Filter and Search Bar */}
      <div className="bg-white border border-slate-100 rounded-2xl p-5 shadow-3xs space-y-4">
        <div className="flex flex-col sm:flex-row gap-3">
          {/* Search bar */}
          <div className="relative flex-1">
            <Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" />
            <input
              type="text"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Search by keywords, subject terms or rationales..."
              className="w-full pl-9 pr-4 py-2 bg-slate-50 border border-slate-150 focus:border-indigo-500 rounded-xl text-xs outline-hidden text-slate-700"
            />
          </div>

          <button
            onClick={() => {
              setSearchTerm('');
              setSubjectFilter('all');
              setLangFilter('all');
              setDiffFilter('all');
              setSelectedIds({});
            }}
            className="px-4 py-2 text-xs text-indigo-650 font-bold hover:bg-indigo-50 rounded-xl transition-colors shrink-0"
          >
            Clear Filters
          </button>
        </div>

        {/* Dropdowns */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          {/* Subject Filter */}
          <div className="space-y-1">
            <span className="text-[9px] font-bold text-slate-400 uppercase">Subject Category</span>
            <select
              value={subjectFilter}
              onChange={(e) => setSubjectFilter(e.target.value)}
              className="w-full p-2 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-650"
            >
              {subjectsList.map((sub, sIdx) => (
                <option key={sIdx} value={sub}>
                  {sub === 'all' ? 'All Subjects (அனைத்து பாடங்கள்)' : sub}
                </option>
              ))}
            </select>
          </div>

          {/* Lang Filter */}
          <div className="space-y-1">
            <span className="text-[9px] font-bold text-slate-400 uppercase">Language Medium</span>
            <select
              value={langFilter}
              onChange={(e) => setLangFilter(e.target.value)}
              className="w-full p-2 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-650"
            >
              <option value="all">All Languages</option>
              <option value="bilingual">Bilingual Only</option>
              <option value="english">English Only</option>
              <option value="tamil">Tamil Only</option>
            </select>
          </div>

          {/* Difficulty Filter */}
          <div className="space-y-1">
            <span className="text-[9px] font-bold text-slate-400 uppercase">Difficulty Standard</span>
            <select
              value={diffFilter}
              onChange={(e) => setDiffFilter(e.target.value)}
              className="w-full p-2 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-650"
            >
              <option value="all">All Difficulties</option>
              <option value="easy">Easy</option>
              <option value="medium">Medium</option>
              <option value="hard">Hard</option>
            </select>
          </div>
        </div>
      </div>

      {/* Questions list container */}
      <div className="bg-white border border-slate-100 rounded-2xl overflow-hidden shadow-xs">
        {/* List Header control */}
        <div className="bg-slate-50 px-4 py-3 border-b border-slate-100 flex items-center justify-between">
          <div className="flex items-center gap-2 select-none">
            <button
              onClick={toggleSelectAll}
              className="text-slate-400 hover:text-slate-600 p-1"
              title="Select all filtered"
            >
              <CheckSquare className="h-4.5 w-4.5" />
            </button>
            <span className="text-xs text-slate-500 font-bold">
              Found {filteredQuestions.length} Questions
            </span>
          </div>

          {selectedCount > 0 && (
            <button
              onClick={handleAssemble}
              className="px-3.5 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-3xs font-black shadow-xs tracking-wider uppercase inline-flex items-center gap-1 transition-all"
            >
              <Play className="h-3 w-3 fill-current" />
              Assemble practice exam ({selectedCount})
            </button>
          )}
        </div>

        {/* Rows */}
        {filteredQuestions.length === 0 ? (
          <div className="p-12 text-center text-slate-500 text-sm">
            No questions matched your search criteria.
          </div>
        ) : (
          <div className="divide-y divide-slate-100 select-none">
            {filteredQuestions.map((q, idx) => {
              const isSelected = selectedIds[q.id] === true;

              return (
                <div
                  key={q.id}
                  onClick={() => toggleSelect(q.id)}
                  className={`p-4 sm:p-5 flex items-start gap-4 hover:bg-slate-50/55 cursor-pointer transition-colors ${
                    isSelected ? 'bg-indigo-500/5 hover:bg-indigo-500/10' : ''
                  }`}
                >
                  {/* Custom Checkbox */}
                  <div className="pt-0.5 shrink-0 text-slate-400">
                    {isSelected ? (
                      <Check className="h-5 w-5 text-indigo-600 stroke-[3px]" />
                    ) : (
                      <span className="h-4.5 w-4.5 inline-block rounded-xs border border-slate-350 bg-white" />
                    )}
                  </div>

                  {/* Text details */}
                  <div className="space-y-2 flex-1 min-w-0">
                    <div className="flex flex-wrap items-center gap-1.5">
                      <span className="px-2 py-0.5 rounded bg-slate-100 text-slate-600 text-3xs font-bold font-mono">
                        {q.subject}
                      </span>
                      <span className="px-2 py-0.5 rounded bg-amber-50 text-amber-700 text-3xs font-bold uppercase">
                        {q.difficulty}
                      </span>
                      <span className="px-2 py-0.5 rounded bg-emerald-50 text-emerald-700 text-3xs font-bold capitalize">
                        {q.language}
                      </span>
                    </div>

                    <h3 className="text-xs sm:text-sm font-semibold text-slate-800 leading-relaxed whitespace-pre-line">
                      {q.text}
                    </h3>

                    {/* Explanatory preview */}
                    <p className="text-3xs text-slate-400 bg-slate-50 p-2 rounded-lg italic">
                      💡 {q.explanation}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Floating Action footer helper */}
      {selectedCount > 0 && (
        <div className="fixed bottom-6 left-1/2 transform -translate-x-1/2 max-w-sm w-full bg-slate-900 border border-slate-800 text-white rounded-2xl px-5 py-3.5 flex items-center justify-between shadow-xl z-50 animate-slideUp">
          <div className="text-xs select-none">
            <span className="font-bold text-indigo-400">{selectedCount}</span> Questions selected
          </div>
          <button
            onClick={handleAssemble}
            className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-lg text-3xs uppercase tracking-wider inline-flex items-center gap-1.5 transition-all"
            id="btn-bottom-assemble"
          >
            <Play className="h-3 w-3 fill-current" />
            Start Exam
          </button>
        </div>
      )}
    </div>
  );
}
